package co.powergym.view.socio;

import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.UIManager;
import java.awt.Color;
import javax.swing.DropMode;

public class SocioBusquedaView extends JFrame {

	private JPanel contentPane;
	public JTextField textField_identidad;
	public JLabel textField_primerNombre;
	public JLabel textField_telefono;
	public JLabel textField_fechaNacimiento;
	public JButton btnBuscar;
	private JLabel lblFoto;

	/**
	 * Creates new form RegistroSocio
	 */
	public SocioBusquedaView() {

		setTitle("Buscar un socio");
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setBounds(100, 100, 965, 574);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);

		JLabel lblNumeroDeIdentidad = new JLabel("Ingrese el n\u00FAmero de identidad:");
		lblNumeroDeIdentidad.setBounds(39, 69, 220, 20);

		textField_identidad = new JTextField();
		textField_identidad.setBounds(269, 69, 150, 20);
		textField_identidad.setColumns(10);

		JLabel lblBuscarSocio = new JLabel("Buscar Socio");
		lblBuscarSocio.setBounds(172, 21, 364, 25);
		lblBuscarSocio.setHorizontalAlignment(SwingConstants.CENTER);
		lblBuscarSocio.setFont(new Font("Tahoma", Font.PLAIN, 20));

		btnBuscar = new JButton("Buscar");
		btnBuscar.setBounds(429, 68, 117, 23);
		getContentPane().setLayout(null);
		getContentPane().add(lblNumeroDeIdentidad);
		getContentPane().add(textField_identidad);
		getContentPane().add(lblBuscarSocio);
		getContentPane().add(btnBuscar);

		JPanel panel = new JPanel();
		panel.setBorder(new TitledBorder(null, "Socio", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		panel.setBounds(39, 100, 305, 295);
		getContentPane().add(panel);
		panel.setLayout(null);

		textField_primerNombre = new JLabel();
		textField_primerNombre.setText("Primer nombre");
		textField_primerNombre.setBounds(10, 193, 275, 20);
		panel.add(textField_primerNombre);

		textField_fechaNacimiento = new JLabel();
		textField_fechaNacimiento.setText("Fecha de nacimiento");
		textField_fechaNacimiento.setBounds(10, 224, 275, 20);
		panel.add(textField_fechaNacimiento);

		textField_telefono = new JLabel();
		textField_telefono.setText("Telefono");
		textField_telefono.setBounds(10, 255, 275, 20);
		panel.add(textField_telefono);

		JPanel panel_1 = new JPanel();
		panel_1.setBorder(null);
		panel_1.setBounds(68, 18, 167, 164);
		panel.add(panel_1);
		panel_1.setLayout(null);

		lblFoto = new JLabel("");
		lblFoto.setBounds(10, 11, 147, 142);
		panel_1.add(lblFoto);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	public JTextField getTextField_identidad() {
		return textField_identidad;
	}

	public JLabel getTextField_primerNombre() {
		return textField_primerNombre;
	}

	public JLabel getTextField_fechaNacimiento() {
		return textField_fechaNacimiento;
	}

	public JLabel getTextField_telefono() {
		return textField_telefono;
	}

	public JButton getBtnBuscar() {
		return btnBuscar;
	}

	public JLabel getLblFoto() {
		return lblFoto;
	}
}
