package co.powergym.view.socio;

import java.awt.Font;
import java.awt.Image;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.UIManager;
import java.awt.Color;
import javax.swing.DropMode;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class SocioConsultaEntradaView extends JFrame {

	private JPanel contentPane;
	public JLabel textField_primerNombre;
	public JLabel textField_telefono;
	public JLabel textField_fechaNacimiento;
	private JLabel lblFoto;
	private JPanel panel_3;

	/**
	 * Creates new form RegistroSocio
	 */
	public SocioConsultaEntradaView() {

		setTitle("Buscar un socio");
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setBounds(100, 100, 610, 540);
		contentPane = new JPanel();
		contentPane.setLocation(-254, -100);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);

		JLabel lblBuscarSocio = new JLabel("Registrar entrada");
		lblBuscarSocio.setBounds(25, 21, 550, 25);
		lblBuscarSocio.setHorizontalAlignment(SwingConstants.CENTER);
		lblBuscarSocio.setFont(new Font("Tahoma", Font.PLAIN, 20));
		getContentPane().setLayout(null);
		getContentPane().add(lblBuscarSocio);

		JPanel panel = new JPanel();
		panel.setBorder(new TitledBorder(null, "Socio", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		panel.setBounds(74, 100, 210, 245);
		getContentPane().add(panel);
		panel.setLayout(null);

		textField_primerNombre = new JLabel();
		textField_primerNombre.setFont(new Font("Avenir Black", Font.BOLD, 11));
		textField_primerNombre.setHorizontalAlignment(SwingConstants.CENTER);
		textField_primerNombre.setText("Primer nombre");
		textField_primerNombre.setBounds(5, 191, 200, 15);
		panel.add(textField_primerNombre);

		textField_fechaNacimiento = new JLabel();
		textField_fechaNacimiento.setFont(new Font("Avenir Black", Font.BOLD, 11));
		textField_fechaNacimiento.setHorizontalAlignment(SwingConstants.CENTER);
		textField_fechaNacimiento.setText("Fecha de nacimiento");
		textField_fechaNacimiento.setBounds(5, 206, 200, 15);
		panel.add(textField_fechaNacimiento);

		textField_telefono = new JLabel();
		textField_telefono.setFont(new Font("Avenir Black", Font.BOLD, 11));
		textField_telefono.setHorizontalAlignment(SwingConstants.CENTER);
		textField_telefono.setText("Telefono");
		textField_telefono.setBounds(5, 221, 200, 15);
		panel.add(textField_telefono);
		
				lblFoto = new JLabel("");
				lblFoto.setBounds(30, 30, 150, 150);
				panel.add(lblFoto);
				lblFoto.setIcon(new ImageIcon(((new ImageIcon("image/avatar.png")).getImage()).getScaledInstance(lblFoto.getHeight(), lblFoto.getHeight(), java.awt.Image.SCALE_AREA_AVERAGING)));
				
				JPanel panel_1 = new JPanel();
				panel_1.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Membresia activa", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
				panel_1.setBounds(25, 356, 550, 140);
				contentPane.add(panel_1);
				
				panel_3 = new JPanel();
				panel_3.setLayout(null);
				panel_3.setBorder(new LineBorder(new Color(0, 0, 0)));
				panel_3.setBounds(312, 100, 210, 245);
				contentPane.add(panel_3);
				
				JLabel label = new JLabel("");
				label.setBounds(30, 30, 150, 150);
				panel_3.add(label);
				
				JLabel lblHuella = new JLabel();
				lblHuella.setText("Huella");
				lblHuella.setHorizontalAlignment(SwingConstants.CENTER);
				lblHuella.setFont(new Font("Avenir Black", Font.BOLD, 11));
				lblHuella.setBounds(10, 191, 200, 15);
				panel_3.add(lblHuella);
				
				JButton btnNewButton = new JButton("Registrar entrada");
				
				btnNewButton.setBounds(312, 66, 210, 23);
				contentPane.add(btnNewButton);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	

	public JLabel getTextField_primerNombre() {
		return textField_primerNombre;
	}

	public JLabel getTextField_fechaNacimiento() {
		return textField_fechaNacimiento;
	}

	public JLabel getTextField_telefono() {
		return textField_telefono;
	}

	

	public JLabel getLblFoto() {
		return lblFoto;
	}
}
