package co.powergym.view;

import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class BusquedaSocio extends JInternalFrame{
	
	public JTextField textField_identidad;
	public JTextField textField_primerNombre;
	public JTextField textField_segundoNombre;
	public JTextField textField_primerApellido;
	public JTextField textField_segundoApellido;
	public JTextField textField_telefono;
	public JTextField textField_correoElectronico;
	public JTextField textField_fechaNacimiento;
	public JTextField textField_genero;
	public JButton btnBuscar;  
	
	/**
     * Creates new form RegistroSocio
     */
    public BusquedaSocio() {
    	setResizable(false);
    	setTitle("Buscar un socio");
    	setClosable(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
       
        JLabel lblNumeroDeIdentidad = new JLabel("Ingrese el nùmero de identidad:");
        
        textField_identidad = new JTextField();
        textField_identidad.setColumns(10);
        
        JLabel lblNombre = new JLabel("Primer nombre:");
        
        textField_primerNombre = new JTextField();
        textField_primerNombre.setColumns(10);
        
        JLabel lblSegundoNombre = new JLabel("Segundo nombre:");
        
        textField_segundoNombre = new JTextField();
        textField_segundoNombre.setColumns(10);
        
        JLabel lblPrimerApellido = new JLabel("Primer apellido:");
        
        textField_primerApellido = new JTextField();
        textField_primerApellido.setColumns(10);
        
        JLabel lblSegundoNombre_1 = new JLabel("Segundo apellido:");
        
        textField_segundoApellido = new JTextField();
        textField_segundoApellido.setColumns(10);
        
        JLabel lblFechaDeNacimiento = new JLabel("Fecha de nacimiento:");
        
        JLabel lblNewLabel = new JLabel("Tel\u00E9fono:");
        
        textField_telefono = new JTextField();
        textField_telefono.setColumns(10);
        
        JLabel lblCorreoElectronico = new JLabel("Correo electr\u00F3nico:");
        
        textField_correoElectronico = new JTextField();
        textField_correoElectronico.setColumns(10);
        
        JLabel lblGenero = new JLabel("Genero:");
        
        textField_genero = new JTextField();
        textField_genero.setColumns(10);
        
        JLabel lblBuscarSocio = new JLabel("Buscar Socio");
        lblBuscarSocio.setHorizontalAlignment(SwingConstants.CENTER);
        lblBuscarSocio.setFont(new Font("Tahoma", Font.PLAIN, 20));
        
        btnBuscar = new JButton("Buscar");
        
        textField_fechaNacimiento = new JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblPrimerApellido, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblCorreoElectronico, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblFechaDeNacimiento, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblNombre, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblNumeroDeIdentidad))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(textField_primerNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblSegundoNombre))
        				.addComponent(textField_identidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(textField_fechaNacimiento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(textField_primerApellido))
        						.addComponent(textField_correoElectronico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblGenero, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        						.addComponent(lblNewLabel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addComponent(lblSegundoNombre_1, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(textField_segundoNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_segundoApellido)
        				.addComponent(textField_telefono)
        				.addComponent(textField_genero, 0, 114, Short.MAX_VALUE))
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(83)
        			.addComponent(lblBuscarSocio, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        			.addGap(83))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(218)
        			.addComponent(btnBuscar, GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        			.addGap(195))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(32)
        			.addComponent(lblBuscarSocio)
        			.addGap(40)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_identidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNumeroDeIdentidad))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_primerNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNombre)
        				.addComponent(textField_segundoNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblSegundoNombre))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblPrimerApellido)
        				.addComponent(textField_primerApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_segundoApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblSegundoNombre_1))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(lblFechaDeNacimiento)
        					.addComponent(lblNewLabel)
        					.addComponent(textField_telefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(textField_fechaNacimiento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_correoElectronico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblCorreoElectronico)
        				.addComponent(textField_genero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblGenero))
        			.addGap(18)
        			.addComponent(btnBuscar)
        			.addContainerGap(94, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
	public JTextField getTextField_primerApellido() {
		return textField_primerApellido;
	}
	public JTextField getTextField_identidad() {
		return textField_identidad;
	}
	public JTextField getTextField_correoElectronico() {
		return textField_correoElectronico;
	}
	public JTextField getTextField_primerNombre() {
		return textField_primerNombre;
	}
	public JTextField getTextField_fechaNacimiento() {
		return textField_fechaNacimiento;
	}
	public JTextField getTextField_genero() {
		return textField_genero;
	}
	public JTextField getTextField_telefono() {
		return textField_telefono;
	}
	public JTextField getTextField_segundoNombre() {
		return textField_segundoNombre;
	}
	public JTextField getTextField_segundoApellido() {
		return textField_segundoApellido;
	}
	public JButton getBtnBuscar() {
		return btnBuscar;
	}

}
