/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.powergym.view;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;

import java.awt.Font;
import java.beans.PropertyVetoException;

import javax.swing.SwingConstants;
import javax.swing.JButton;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author berna
 */
public class RegistroSocio extends JInternalFrame {
	public JTextField textField_identidad;
	public JTextField textField_primerNombre;
	public JTextField textField_segundoNombre;
	public JTextField textField_primerApellido;
	public JTextField textField_segundoApellido;
	public JTextField textField_telefono;
	public JTextField textField_correoElectronico;
	public JDateChooser dateChooser_fechaNacimiento;
	public JComboBox comboBox_genero;
	public JButton btnRegistrar;

    /**
     * Creates new form RegistroSocio
     */
    public RegistroSocio() {
    	setResizable(false);
    	setTitle("Registrar un nuevo socio");
    	setClosable(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
       
        JLabel lblNumeroDeIdentidad = new JLabel("Numero de identidad:");
        
        textField_identidad = new JTextField();
        textField_identidad.setColumns(10);
        
        JLabel lblNombre = new JLabel("Primer nombre:");
        
        textField_primerNombre = new JTextField();
        textField_primerNombre.setColumns(10);
        
        JLabel lblSegundoNombre = new JLabel("Segundo nombre:");
        
        textField_segundoNombre = new JTextField();
        textField_segundoNombre.setColumns(10);
        
        JLabel lblPrimerApellido = new JLabel("Primer apellido:");
        
        textField_primerApellido = new JTextField();
        textField_primerApellido.setColumns(10);
        
        JLabel lblSegundoNombre_1 = new JLabel("Segundo apellido:");
        
        textField_segundoApellido = new JTextField();
        textField_segundoApellido.setColumns(10);
        
        JLabel lblFechaDeNacimiento = new JLabel("Fecha de nacimiento:");
        
        JLabel lblNewLabel = new JLabel("Tel\u00E9fono:");
        
        textField_telefono = new JTextField();
        textField_telefono.setColumns(10);
        
        JLabel lblCorreoElectronico = new JLabel("Correo electr\u00F3nico:");
        
        textField_correoElectronico = new JTextField();
        textField_correoElectronico.setColumns(10);
        
        JLabel lblGenero = new JLabel("Genero:");
        
        comboBox_genero = new JComboBox();
        comboBox_genero.addItem("Femenino");
        comboBox_genero.addItem("Masculino");
        
        JLabel lblRegistrarSocio = new JLabel("Registrar Socio");
        lblRegistrarSocio.setHorizontalAlignment(SwingConstants.CENTER);
        lblRegistrarSocio.setFont(new Font("Tahoma", Font.PLAIN, 20));
        
        btnRegistrar = new JButton("Registrar");
        
        dateChooser_fechaNacimiento = new JDateChooser();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblPrimerApellido, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblCorreoElectronico, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblFechaDeNacimiento, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblNombre, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        				.addComponent(lblNumeroDeIdentidad))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(textField_primerNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblSegundoNombre))
        				.addComponent(textField_identidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(dateChooser_fechaNacimiento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(textField_primerApellido))
        						.addComponent(textField_correoElectronico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblGenero, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        						.addComponent(lblNewLabel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addComponent(lblSegundoNombre_1, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(textField_segundoNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_segundoApellido)
        				.addComponent(textField_telefono)
        				.addComponent(comboBox_genero, 0, 114, Short.MAX_VALUE))
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(83)
        			.addComponent(lblRegistrarSocio, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        			.addGap(83))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(218)
        			.addComponent(btnRegistrar, GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        			.addGap(195))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(32)
        			.addComponent(lblRegistrarSocio)
        			.addGap(40)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_identidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNumeroDeIdentidad))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_primerNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNombre)
        				.addComponent(textField_segundoNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblSegundoNombre))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblPrimerApellido)
        				.addComponent(textField_primerApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_segundoApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblSegundoNombre_1))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(lblFechaDeNacimiento)
        					.addComponent(lblNewLabel)
        					.addComponent(textField_telefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(dateChooser_fechaNacimiento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_correoElectronico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblCorreoElectronico)
        				.addComponent(comboBox_genero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblGenero))
        			.addGap(18)
        			.addComponent(btnRegistrar)
        			.addContainerGap(94, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
	public JTextField getTextField_primerApellido() {
		return textField_primerApellido;
	}
	public JTextField getTextField_identidad() {
		return textField_identidad;
	}
	public JTextField getTextField_correoElectronico() {
		return textField_correoElectronico;
	}
	public JTextField getTextField_primerNombre() {
		return textField_primerNombre;
	}
	public JDateChooser getDateChooser_fechaNacimiento() {
		return dateChooser_fechaNacimiento;
	}
	public JComboBox getComboBox_genero() {
		return comboBox_genero;
	}
	public JTextField getTextField_telefono() {
		return textField_telefono;
	}
	public JTextField getTextField_segundoNombre() {
		return textField_segundoNombre;
	}
	public JTextField getTextField_segundoApellido() {
		return textField_segundoApellido;
	}
	public JButton getBtnRegistrar() {
		return btnRegistrar;
	}
}
